name: "Tellor Tipper"
description: "Automate tips to Tellor Oracle with Github Actions"
inputs:
  network: #mainnet or rinkeby
    description: "ethereum network to tip to"
    required: true
    default: "mainnet"
  requestID: #ID of tip
    description: "ID of Tip"
    required: true
  dataFreshness:
    description: "the longest duration of time you would wait before requesting new data"
    required: false
outputs:
  time: #id of output
    description: "Timestamp"
runs:
  using: "docker"
  main: "Dockerfile"